import { useState } from 'react';
import Head from 'next/head'
import Board from '@/components/game-board/board'
//import styles from '@/styles/Home.module.css'

export default function Home() {

  let [moves, setMoves] = useState(
    ["","","",
    "","","",
    "","","",]);

  return (
    <>
      <Head>
        <title>Triquicool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>
        <a 
        className='new-game-title' 
        onClick={() => setMoves(["","","","","","","","","",])}
        >Clean Board</a>
      </h2>
      <Board 
        moves = {moves}
        setMoves = {setMoves}
        />
    </>
  )
}
